Using performancemonitor to generate system stats
https://github.com/alange0001/performancemonitor

diff --git a/run_environment b/run_environment
--- a/run_environment
+++ b/run_environment
@@ -4,20 +4,38 @@
 # File run_base
 #
 
-DIR_BASE=$(cd `dirname $0` && echo $PWD)
-[ -z "$DIR_BASE" ] && exit 1
-DIR_YCSB="$DIR_BASE/../YCSB"
-DIR_ROCKS="$DIR_BASE/../rocksdb.bak"
+ulimit -n 1048576
 
-export PATH="$PATH:$DIR_BASE/build"
-export PATH="$PATH:$DIR_YCSB/bin"
-export PATH="$PATH:$DIR_ROCKS"
+FAILED=0
+
+function test_dir() {
+	if [ ! -d "$1" ]; then
+		echo "Directory not found: $1" >&2
+		FAILED=1
+		return 1
+	fi
+	return 0
+}
+
+DIR_BASE="$PWD"
+[ -z "$DIR_BASE" ] && exit 1
+
+DIR_YCSB="$DIR_BASE/../YCSB"
+DIR_ROCKS="$DIR_BASE/../rocksdb"
+
+test_dir "$DIR_BASE/build" && export PATH="$PATH:$DIR_BASE/build"
+test_dir "$DIR_YCSB/bin"   && export PATH="$PATH:$DIR_YCSB/bin"
+test_dir "$DIR_ROCKS"      && export PATH="$PATH:$DIR_ROCKS"
 
 DIR_WORK="/media/auto/work"
+test_dir "$DIR_WORK"
+
 DIR_DB_BENCH="$DIR_WORK/rocksdb"
 DIR_DB_YCSB="$DIR_WORK/rocksdb_ycsb"
 DIR_AT="$DIR_WORK/tmp"
+test_dir "$DIR_AT"
 
 DIR_BACKUP="/media/auto/work2"
+test_dir "$DIR_BACKUP"
 
 IO_DEVICE="nvme0n1"
